### ISSUE TITLE
Result is werid

### ISSUE THREAD

**Issue by jeremykid** [benchling/clustalo-python#3]
I run 

```
from clustalo import clustalo
input = {
    'seq1': 'AAAAAAAA',
    'seq2': 'AGAGAGAG'
}
aligned = clustalo(input)
# aligned is a dict of aligned sequences:
#   seq1: AAAAAAAA
#   seq2: AGAGAGAG
```

Is this correct?

**Comment by alangpierce** [comment]
Hi @jeremykid ! As far as I can tell, this is the expected behavior.

Here's another Clustal Omega tool that gives the same results: https://www.ebi.ac.uk/Tools/msa/clustalo/

I gave it this input:
```
>seq1
AAAAAAAA
>seq2
AGAGAGAG
```
and it gave the same result (inserted no gaps). I tried a few other online alignment tools/algorithms and they seem to give the same result.

Generally, alignment algorithms use a scoring system and try to line up the sequences using gaps in a way that maximizes the score. A mismatch has a penalty, and inserting a gap also has a penalty. In this case, there isn't really a way to line up the sequences any better than they currently are, so the clustal omega algorithm ends up not inserting any gaps at all.

Note that this tool does not directly compute a consensus sequence or mark mismatches, it just does its best to align the sequence that you give it.

Hope that helps explain things. Feel free to re-open if you think there may be a problem with the tool (or consider reporting a bug to the Clustal Omega maintainers; this GitHub project is a small library that makes it easy to use the Clustal Omega tool from Python).
